server.port=${SERVER_PORT:8081}

app.public_key=${APP_PUBLIC_KEY}
app.private_key=${APP_PRIVATE_KEY}
app.terminal_id=${APP_TERMINAL_ID}
app.client_id=${APP_CLIENT_ID}
app.client_secret=${APP_CLIENT_SECRET}
app.serial_id=${APP_SERIAL_ID}
app.version=${APP_VERSION:v1}
app.password=${APP_PASSWORD}
app.base_url=${APP_BASE_URL:https://dev.interswitch.io/api/v1/phoenix/}
app.billers_base_url=${APP_BILLERS_BASE_URL:https://dev.interswitch.io/api/v1/phoenix/gateway/qt-api/Biller/}
